# Generated by Django 4.2.7 on 2024-05-02 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_remove_companiesteam_member_companiesteam_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companiesteam',
            name='members',
        ),
        migrations.AddField(
            model_name='companiesteam',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
