# Generated by Django 4.2.7 on 2023-11-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminusertype_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUserType',
        ),
    ]
