# Generated by Django 5.0.6 on 2024-06-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_available',
        ),
    ]
