# Generated by Django 5.0.6 on 2024-06-03 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentkeypoints',
            old_name='content',
            new_name='keypoints',
        ),
        migrations.RemoveField(
            model_name='documentkeypoints',
            name='company',
        ),
        migrations.RemoveField(
            model_name='documentkeypoints',
            name='prompt_text',
        ),
    ]
