# Generated by Django 4.2.7 on 2024-05-14 06:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_email_adminuser_admin'),
        ('departments', '0002_alter_departmentsdocuments_added_by'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentkeypoints',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keypoint_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='documentkeypoints',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departmentsdocuments'),
        ),
        migrations.AlterField(
            model_name='documentkeypoints',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentquiz',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='documentquiz',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departmentsdocuments'),
        ),
        migrations.AlterField(
            model_name='documentquiz',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_document', to='departments.departmentsdocuments'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
