# Generated by Django 5.0.6 on 2024-05-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentkeypoints',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='documentquiz',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='documentsummary',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='quizquestions',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
