# Generated by Django 4.2.7 on 2024-05-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentkeypoints_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsummary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
