# Generated by Django 5.0.6 on 2024-06-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_content_documentkeypoints_keypoints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentkeypoints',
            name='is_active',
        ),
    ]
