# Generated by Django 5.0.6 on 2024-08-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_scheduledetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledetail',
            old_name='department_id',
            new_name='document_id',
        ),
    ]
