# Generated by Django 4.2.7 on 2023-11-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsummary',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='prompt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
