# Generated by Django 4.2.7 on 2024-05-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_departmentsdocuments_added_by'),
        ('documents', '0003_documentsummary_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentkeypoints',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentquiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departmentsdocuments'),
        ),
    ]
