# Generated by Django 5.0.6 on 2024-06-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_documentkeypoints_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentquiz',
            old_name='content',
            new_name='quiz',
        ),
        migrations.RemoveField(
            model_name='documentquiz',
            name='company',
        ),
        migrations.RemoveField(
            model_name='documentquiz',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='documentquiz',
            name='prompt_text',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='company',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='document',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='is_active',
        ),
    ]
