# Generated by Django 5.0.6 on 2025-01-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_department_id_scheduledetail_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledetail',
            name='question_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduledetail',
            name='quiz_id',
            field=models.UUIDField(null=True),
        ),
    ]
