# Generated by Django 4.2.7 on 2023-11-30 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documentsummary_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsummary',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.userdocuments'),
        ),
        migrations.CreateModel(
            name='DocumentKeyPoints',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('prompt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.userdocuments')),
            ],
        ),
    ]
