# Generated by Django 5.0.6 on 2024-06-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_content_documentquiz_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentkeypoints',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentquiz',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
