# Generated by Django 4.2.7 on 2024-05-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentkeypoints_is_active_documentquiz_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsummary',
            name='is_active',
        ),
    ]
