# Generated by Django 5.0.6 on 2025-01-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_userdocuments_avg_time_to_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocuments',
            name='avg_time_to_complete',
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='duedate',
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='overview',
        ),
    ]
