# Generated by Django 5.0.6 on 2024-06-13 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_company_id'),
        ('departments', '0002_departmentsdocuments_assigned_users'),
        ('documents', '0005_documentkeypoints_prompt_documentquiz_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquiz',
            name='upload',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='KeypointsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.adminuser')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departmentsdocuments')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.adminuser')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departmentsdocuments')),
            ],
        ),
    ]
