# Generated by Django 4.2.7 on 2023-12-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documentsummary_document_documentkeypoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentQuiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('prompt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.AlterModelOptions(
            name='documentkeypoints',
            options={'verbose_name': 'Keypoints', 'verbose_name_plural': 'Keypoints'},
        ),
        migrations.AlterModelOptions(
            name='documentsummary',
            options={'verbose_name': 'Summary', 'verbose_name_plural': 'Summary'},
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='user_id',
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('option_1', models.CharField(blank=True, max_length=255, null=True)),
                ('option_2', models.CharField(blank=True, max_length=255, null=True)),
                ('option_3', models.CharField(blank=True, max_length=255, null=True)),
                ('option_4', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(blank=True, max_length=2, null=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.userdocuments')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentquiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='documentquiz',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.userdocuments'),
        ),
    ]
