# Generated by Django 5.0.6 on 2024-06-13 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentquiz_upload_keypointscount_summarycount'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=10)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.companiesteam')),
            ],
            options={
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
