# Generated by Django 4.2.7 on 2024-01-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentkeypoints_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestions',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='quizquestions',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
