# Generated by Django 5.0.6 on 2025-01-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_rename_avg_time_to_complete_userdocuments_avgcompletiontime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocuments',
            name='avgCompletionTime',
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='dueDate',
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='overview',
        ),
    ]
