# Generated by Django 4.2.7 on 2024-05-01 14:28

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=50)),
                ('company_id', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('state_or_province', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=10)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
