# Generated by Django 4.2.7 on 2024-05-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_admins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='admins',
            new_name='admin',
        ),
    ]
