# Generated by Django 4.2.7 on 2024-05-02 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0005_rename_admins_company_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='admin',
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_admin', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company')),
            ],
            options={
                'verbose_name': 'Company Admin',
                'verbose_name_plural': 'Company Admins',
            },
        ),
    ]
