# Generated by Django 4.2.7 on 2024-05-02 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0007_adminuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='admin',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='admin',
            field=models.ManyToManyField(related_name='team_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
