# Generated by Django 4.2.7 on 2024-05-02 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0008_remove_adminuser_admin_adminuser_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='admin',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
