# Generated by Django 4.2.7 on 2024-05-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_adminuser_admin_adminuser_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='admin',
            new_name='email',
        ),
    ]
