# Generated by Django 4.2.7 on 2024-05-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_rename_company_logo_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='public/static/company_logos/OneColumbia.jpeg', null=True, upload_to='company_logos/'),
        ),
    ]
