# Generated by Django 4.2.7 on 2024-05-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_remove_companiesteam_members_companiesteam_members'),
        ('company', '0009_remove_adminuser_admin_adminuser_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.UUIDField(default=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_added_by', to='company.adminuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_company', to='company.company')),
                ('users', models.ManyToManyField(to='teams.companiesteam')),
            ],
            options={
                'verbose_name': 'Company Department',
                'verbose_name_plural': 'Company Departments',
            },
        ),
    ]
