# Generated by Django 5.0.6 on 2024-06-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentsdocuments',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_documents', to='teams.companiesteam'),
        ),
    ]
