# Generated by Django 5.0.6 on 2024-05-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentsdocuments',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
