# Generated by Django 5.0.6 on 2024-07-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentsdocuments',
            name='schedule_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
