# Generated by Django 5.0.6 on 2024-05-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_created_date_departmentsdocuments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentsdocuments',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
