# Generated by Django 4.2.7 on 2024-05-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_departments_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='added_by',
        ),
    ]
