# Generated by Django 4.2.7 on 2024-05-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_adminuser_admin_adminuser_admin'),
        ('departments', '0004_remove_departments_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='added_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_added_by', to='company.adminuser'),
        ),
    ]
