# Generated by Django 4.2.7 on 2024-05-05 16:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_rename_admin_adminuser_email'),
        ('departments', '0005_departments_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentsDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('published', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_added_by', to='company.adminuser')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_departments', to='departments.departments')),
            ],
            options={
                'verbose_name': 'Company Document',
                'verbose_name_plural': 'Company Documents',
            },
        ),
    ]
