# Generated by Django 4.2.7 on 2024-05-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_departmentsdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentsdocuments',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
