# Generated by Django 4.2.7 on 2024-05-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_companiesteam_members_companiesteam_members'),
        ('departments', '0007_departmentsdocuments_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='teams.companiesteam'),
        ),
    ]
