# Generated by Django 4.2.7 on 2024-05-08 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0008_alter_departments_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='added_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_added_by_main', to=settings.AUTH_USER_MODEL),
        ),
    ]
